### ISSUE TITLE
npm run dev后dist文件夹始终没有app.js、app.json、app.wxss和project.config.json

### ISSUE THREAD

**Issue by xianxingzhe** [armyja/mpvue-zanui#17]
命令行提示
`No parser and no filepath given, using 'babylon' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.`

**Comment by armyja** [comment]
确认一下 node 和 npm 版本。
$ node -v
v8.9.0

$ npm -v
5.6.0

**Comment by xianxingzhe** [comment]
$ node -v
v8.9.1

$ npm -v
6.2.0

**Comment by armyja** [comment]
npm 降下级
npm i npm@5.6.0

**Comment by xianxingzhe** [comment]
非常感谢，终于可以啦

**Comment by Mistergong** [comment]
可以用了吗？我npm降级之后还是这个问题，node 也要降级吗？
