### ISSUE TITLE
版本和你的统一了之后，npm run dev仍然报错，微信小程序必须文件编译不出来----来自同在深圳的工程师朋友

### ISSUE THREAD

**Issue by Mistergong** [armyja/mpvue-zanui#18]
node 版本 `$ node -v   //v8.9.0`
npm 版本 `$ npm -v   //5.6.0`
可是npm run dev后还是报错
`No parser and no filepath given, using 'babylon' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.`
可否指点一下迷津？

**Comment by armyja** [comment]
重新clone并npm i

**Comment by armyja** [comment]
更新新版本mpvue后会出现该问题，正在解决中

**Comment by armyja** [comment]
[function getEntry (dir, entryFile) {](https://github.com/armyja/mpvue-zanui/blob/7d1542f44864003bbfe6860d321f1d2698a4064f/build/webpack.base.conf.js#L11)

修改为

```
function getEntry (rootSrc, pattern) {
  var files = glob.sync(path.resolve(rootSrc, pattern))
  return files.reduce((res, file) => {
    var info = path.parse(file)
    var key = info.dir.slice(rootSrc.length + 1) + '/' + info.name
    res[key] = path.resolve(file)
    return res
  }, {})
}
```

**Comment by Mistergong** [comment]
十分感谢！辛苦了

**Comment by Mistergong** [comment]
文件夹删掉后，重新clone了一份跑起来，可还是相同的错误o.o!。版本无修改，应该是有点其他问题。
