### ISSUE TITLE
打包出来，微信小程序必要文件app.js/app.json/app.wxss等缺失

### ISSUE THREAD

**Issue by Mistergong** [armyja/mpvue-zanui#21]
`$ node -v //8.9.0`
`$ npm -v //5.6.0`
`npm run dev`会报warning: No parser and no filepath given, using 'babylon' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.
最后编译是成功的
`Starting to optimize CSS...
 DONE  Compiled successfully in 6515ms15:15:59`
然而dist里面却只有components/pages/static三个文件夹，微信小程序要用的app.js/app.json/app.wxss等都没有
同样的环境跑mpvue-weui是可以的，这里问题出在了哪里？

**Comment by armyja** [comment]
报 warning 是正常的，这个我不知道怎么处理。
亲测 clone 后是有 app.js/app.json/app.wxss 的，你再重新试试。
