### ISSUE TITLE
真机调试，操作反馈模块报错

### ISSUE THREAD

**Issue by AnShengqiang** [armyja/mpvue-zanui#3]
在真机上开启调试，出现vConsole后，下面的操作反馈模块的组件大多会报错：
thirdScriptError
Converting circular structure to JSON

不开启调试状态的时候没有问题。

**Comment by armyja** [comment]
感谢测试，确实会出现 `cannot read property 'call' of undefined` thirdScriptError、Converting circular structure to JSON 的问题。原因是组件之间的通信写法不是很规范，比如 [switch 组件](https://github.com/armyja/mpvue-zanui/blob/133008874164a4f8e87e17884cec67af6813eac8/src/components/zan/switch.vue#L48)  
 [Toptips](https://github.com/armyja/mpvue-zanui/blob/c550555f50b146544dff06c119bb552d607ec996/src/pages/zan_toptips/index.vue#L31)  [Dialog](https://github.com/armyja/mpvue-zanui/blob/eb24d64af2687047caac786c991cd596ce065987/src/components/zan/dialog.vue#L146)。建议使用 Vuex 或者 [emit](https://github.com/armyja/mpvue-zanui/blob/eb24d64af2687047caac786c991cd596ce065987/src/components/zan/actionsheet.vue#L113) 来触发事件。

**Comment by cottengc** [comment]
有什么办法可以解决吗？ 我也遇到了 toast topTips 在调试模式下 会有问题
