### ISSUE TITLE
npm包 stepper组件有BUG

### ISSUE THREAD

**Issue by wjkang** [armyja/mpvue-zanui#5]
<input
      class="zan-stepper__text"
      :class="{ 'zan-stepper--disabled' : min >= max }"
      type="number"
      data-component-id="componentId"
      :data-min="min"
      :data-max="max"
      :value="stepper"
      :disabled="min >= max"
      @blur="_handleZanStepperBlur"
    />
data-component-id没有动态绑定

**Comment by armyja** [comment]
已修复，感谢。
